542-when-updating-station-and-wallet-i-lose-my-accounts
massalabs/station-massa-wallet pull request #578
Opened 2023-08-04 09:22 UTC by Pierregvx

2023-08-04 10:17 UTC, Thykof requested changes

2023-08-04 10:17 UTC, Thykof commented on internal/handler/wallet/getall.go
> +		status := "ok"
we should use a constant variable, the same as the one we use when creating a new account

2023-08-04 10:17 UTC, Thykof commented on internal/handler/wallet/getall.go
> +		modelWalletErr.Status = &status
can we modify `createModelWallet` instead of setting the Status here?

2023-08-04 10:17 UTC, Thykof commented on pkg/wallet/wallet.go
> +	account.Status = "ok"
create a constant variable for "ok"

2023-08-04 10:17 UTC, Thykof commented on pkg/wallet/wallet.go
> +		Nickname: "unknown wallet",
is it possible to get the wallet nickname from the filename?

2023-08-04 10:17 UTC, Thykof commented on web-frontend/src/pages/Index/Index.tsx
> +          `${account}${
```suggestion
        (name: string, index: number) =>
          `${name}${
```

2023-08-04 10:17 UTC, Thykof commented on plugin.zip
remove this

2023-08-04 14:56 UTC, Thykof requested changes

2023-08-04 14:56 UTC, Thykof commented on pkg/wallet/wallet.go
> +	account.Status = "ok"
now you can use it!

2023-08-04 14:56 UTC, Thykof commented on pkg/wallet/wallet.go
> +	nicknameFromFileName = strings.TrimSuffix(nicknameFromFileName, ".yaml")
you can extract this into a function near https://github.com/massalabs/station-massa-wallet/blob/86040bea9ca6414c2087770de7968e2b08548028/pkg/wallet/wallet.go#L389

2023-08-07 07:20 UTC, Thykof commented on pkg/wallet/wallet.go
> +	nicknameFromFileName = strings.TrimSuffix(nicknameFromFileName, ".yaml")
```go
```

2023-08-07 07:22 UTC, Thykof commented on pkg/wallet/wallet.go
> +	nicknameFromFileName = strings.TrimSuffix(nicknameFromFileName, ".yaml")
you can create this function and put it bellow that function: https://github.com/massalabs/station-massa-wallet/blob/86040bea9ca6414c2087770de7968e2b08548028/pkg/wallet/wallet.go#L389

```go
func NicknameFromFilePath(filePath string): string {
	_, nicknameFromFileName := filepath.Split(filePath)
	nicknameFromFileName = strings.TrimPrefix(nicknameFromFileName, "wallet_")
	nicknameFromFileName = strings.TrimSuffix(nicknameFromFileName, ".yaml")

	return nicknameFromFileName
}
```

2023-08-07 13:21 UTC, Thykof commented on pkg/wallet/wallet.go
> +	nicknameFromFileName = strings.TrimSuffix(nicknameFromFileName, ".yaml")
in golang, we usually don't prefix the getter functions with `get`

2023-08-07 13:46 UTC, Thykof approved these changes

2023-08-08 07:53 UTC, pivilartisant approved these changes

2023-08-08 15:22 UTC, merged