extract executesc operation info and-send it to wails popup
massalabs/station-massa-wallet pull request #613
Opened 2023-08-18 08:26 UTC by B-Naoufal

2023-08-18 10:35 UTC, Thykof requested changes

2023-08-18 10:35 UTC, Thykof commented on internal/handler/wallet/sign.go
> +			fmt.Println("Decoded CallSC message successfully")
```suggestion
```

2023-08-18 10:35 UTC, Thykof commented on internal/handler/wallet/sign.go
> +			fmt.Println("Decoded ExecuteSC message successfully")
```suggestion
```

2023-08-18 10:35 UTC, Thykof commented on internal/handler/wallet/sign.go
the function `func (s *walletSign) Handle(params operations.SignParams) middleware.Responder` is too long and too complex. Please split it into multiple small functions to improve code readability and maintainability.

2023-08-18 14:44 UTC, Thykof requested changes

2023-08-18 14:44 UTC, Thykof commented on internal/handler/wallet/sign.go
> +	return promptRequest, nil
```suggestion
	callSC, err := callsc.DecodeMessage(decodedMsg)
	if err == nil && callSC != nil {
		promptRequest = s.prepareCallSCPromptRequest(callSC, wlt)
		return promptRequest, nil
	}
	executeSC, err := executesc.DecodeMessage(decodedMsg)
	if err == nil && executeSC != nil {
		promptRequest = s.prepareExecuteSCPromptRequest(executeSC, wlt)
		return promptRequest, nil
	}

	promptRequest = s.prepareUnknownPromptRequest(wlt)

	return promptRequest, nil
```

2023-08-21 09:21 UTC, Thykof approved these changes

2023-08-21 10:04 UTC, gregLibert approved these changes

2023-08-21 10:11 UTC, merged