Refactor PasswordPrompt
massalabs/station-massa-wallet pull request #621
Opened 2023-08-21 14:13 UTC by pivilartisant

2023-08-22 12:27 UTC, Thykof requested changes
my partial review

2023-08-22 13:05 UTC, pivilartisant commented on wails-frontend/src/pages/PasswordPrompt/Default.tsx
> +    }
let me know if pushed changes are what you expected

2023-08-22 15:34 UTC, mazmassa approved these changes
Thanks for that Paul! 👏

2023-08-22 15:36 UTC, pivilartisant commented
Double checking flow here, pls wait b4 merge !!

2023-08-23 07:28 UTC, Thykof commented
we ignore sonar lint CI

2023-08-23 07:28 UTC, merged