store user files (accounts, assets) into home directory
massalabs/station-massa-wallet pull request #681
Opened 2023-09-07 15:05 UTC by Thykof

2023-09-08 09:14 UTC, thomas-senechal approved these changes

2023-09-10 22:11 UTC, Thykof commented
follow up issue: https://github.com/massalabs/station-massa-wallet/issues/687

2023-09-11 07:45 UTC, thomas-senechal approved these changes

2023-09-11 07:45 UTC, thomas-senechal commented on pkg/wallet/wallet.go
> +			}
I'm not sure this is useful ? 🤔

2023-09-11 07:46 UTC, peterjah requested changes

2023-09-11 08:01 UTC, Thykof commented on main.go
> +			panic(err)
no, good catch

2023-09-11 08:17 UTC, peterjah approved these changes

2023-09-11 08:32 UTC, thomas-senechal approved these changes

2023-09-11 08:36 UTC, merged