Refacto: use new wallet package
massalabs/station-massa-wallet pull request #778
Opened 2023-10-04 22:33 UTC by Thykof

2023-10-23 10:24 UTC, peterjah approved these changes

2023-10-24 09:43 UTC, gregLibert requested changes

2023-10-24 09:43 UTC, gregLibert commented on internal/handler/wallet/sign.go
> +func Xor(a, b []byte) ([]byte, error) {
You should return a memguard object instead

2023-10-24 09:43 UTC, gregLibert commented on internal/handler/wallet/sign.go
> +	correlationID models.CorrelationID,
correlationId should be protected

2023-10-24 09:43 UTC, gregLibert commented on internal/handler/wallet/sign.go
> +		return passwordExpirationTime
Why is it named password ? You should also add a "default" somewhere in its name

2023-10-24 09:43 UTC, gregLibert commented on pkg/prompt/constants.go
> +	InputTypeErr        = "Invalid prompt input type"
You should avoid starting with a capital letter

2023-10-24 13:17 UTC, Thykof commented on internal/handler/wallet/backup.go
> +	acc, err := w.prompterApp.App().WalletManager.GetAccount(params.Nickname)
I don't understand the concern

2023-10-24 22:00 UTC, Thykof commented on internal/handler/wallet/import.go
> +	modelWallet, resp := newAccountModel(*acc)
this code is outaded, but we often do a similar thing:

```go
acc, resp := loadAccount(w.prompterApp.App().Wallet, params.Nickname)
if resp != nil {
    return resp
}
```

should I do instead?

```
acc, errResp := loadAccount(w.prompterApp.App().Wallet, params.Nickname)
if resp != nil {
    return errResp
}
```

2023-10-24 22:13 UTC, Thykof commented on internal/handler/wallet/sign.go
> +		// correlationId = params.Body.CorrelationID
just because I deactivate batch signing it that commit and rework it in the following commit

2023-10-24 22:19 UTC, Thykof commented on internal/handler/wallet/api.go
> +func newErrorResponse(message, code string, status int16) middleware.Responder {
I improve that in another commit: https://github.com/massalabs/station-massa-wallet/pull/778/commits/56f8abc982ae4b7cac717ee483f7588517c56cd4#diff-66951be168e9194414d31aec11c1c1874b271ba8a890c5152baaeaeff5698785

2023-10-24 22:26 UTC, Thykof commented on internal/handler/wallet/sign.go
> +	key := CacheKey(correlationID)
because if one day we decide to change the algorithm to create the cache key, we will need to change the code at multiple location

2023-10-25 12:13 UTC, Thykof commented on internal/handler/wallet/backup.go
> +	acc, err := w.prompterApp.App().WalletManager.GetAccount(params.Nickname)
what question do I need to ask myself to determine that?

2023-10-26 08:36 UTC, gregLibert approved these changes

2023-10-26 13:03 UTC, merged