Account version 0 compatible
massalabs/station-massa-wallet pull request #862
Opened 2023-12-28 17:12 UTC by Thykof

2023-12-29 15:56 UTC, ASAPSegfault requested changes

2023-12-29 15:56 UTC, ASAPSegfault commented on pkg/wallet/account/account_test.go
> +		assert.ErrorContains(t, err, "missing version")
Missing version would be misleading here. According to the test name the version is present, just not handled.

2023-12-29 15:56 UTC, ASAPSegfault commented on pkg/types/encrypted_private_key.go
> +		result := memguard.NewBuffer(64)
Why not using ed25519.PrivateKeySize instead of 64 for more clarity ?

2023-12-29 15:56 UTC, ASAPSegfault commented on pkg/types/encrypted_private_key.go
> +		result := memguard.NewBuffer(64)
Why not using ed25519.PrivateKeySize instead of 64 for more clarity ?

2023-12-29 15:56 UTC, ASAPSegfault commented on pkg/types/encrypted_private_key.go
> +		return nil, fmt.Errorf("unsealing secret: %w", err)
All errors are wrapped, but not the one ligne 181. I suggest wrapping it too.

2024-01-02 21:50 UTC, peterjah approved these changes

2024-01-03 08:54 UTC, ASAPSegfault approved these changes

2024-01-03 09:04 UTC, merged